export const welcome_styles = {
  main_container: {
    display: "flex",
    width: "100%",
    height: "100%",
    justifyContent: "flex-end",
  },
  title_and_logo_container: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
    flexDirection: "row",
  },
  title: {
    fontWeight: "700",
  },
  logo_png: {
    top: -10,
    marginHorizontal: 10,
    width: 40,
    height: 90,
    resizeMode: "contain",
    tintColor: "white",
  },
  bottom_container: {
    alignItems: "center",
    width: "100%",
    height: "auto",
    marginBottom: 64,
  },
  full_button: {
    borderWidth: 2.5,
    borderRadius: 25,
    borderColor: "rgb(204, 204, 204)",
    alignItems: "center",
    width: "75%",
    height: "auto",
    padding: 10,
  },
  full_button_pressed: {
    width: "73.5%",
    borderColor: "rgba(204, 204, 204, 0.66)",
  },
  text_inside_full_button: {},
  text_privacy_note: {
    fontSize: 13,
    fontWeight: "400",
    width: "75%",
    height: "auto",
    lineHeight: 18,
    padding: 18,
    textAlign: "center",
  },
  text_url: {
    fontWeight: "500",
    textDecorationLine: "underline",
  },
};
